version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - DB_URL=mysql://database/alec
  backend:
    build: ./backend
    ports:
      - 8000:8000
  database:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - alec:/data/database
volumes:
  alec:
