version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 8007:8007
  database:
    image: mysql:8
    ports:
      - 3309:3309
   